//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectTable
    {
        public int StudentNo { get; set; }
        public int CategoryID { get; set; }
        public int PrimaryID { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
