//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MailProEntities : DbContext
    {
        public MailProEntities()
            : base("name=MailProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTable> CategoryTable { get; set; }
        public virtual DbSet<ConnectTable> ConnectTable { get; set; }
        public virtual DbSet<FacultyTable> FacultyTable { get; set; }
        public virtual DbSet<StudentTable> StudentTable { get; set; }
        public virtual DbSet<Mails> Mails { get; set; }
        public virtual DbSet<Temp> Temp { get; set; }
        public virtual DbSet<TemplateTable> TemplateTable { get; set; }
    }
}
