//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateTable
    {
<<<<<<< HEAD:MailPro/MailPro/TemplateTable.cs
        public int TemplateID { get; set; }
        public string TemplateURL { get; set; }
        public string TemplateName { get; set; }
<<<<<<< HEAD
<<<<<<< HEAD:MailPro/MailPro/TemplateTable.cs
        public string TemplateImage { get; set; }
=======
>>>>>>> ba1c07d870058e9fc152c107e680f299f4ef66c7:demoDB.Db/user.cs
=======
        public string TemplateURL { get; set; }
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string TemplateImage { get; set; }
>>>>>>> swasti:demoDB.Db/user.cs
=======
        public string TemplateImage { get; set; }
>>>>>>> Rishabh
    }
}
