//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp
    {
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public int StuidentNo { get; set; }
        public string Branch { get; set; }
        public int Section { get; set; }
        public int Year { get; set; }
        public bool IsHosteller { get; set; }
        public bool IsCR { get; set; }
        public string StudentCategory { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int FacultyID { get; set; }
        public int Keys { get; set; }
        public bool IsSelected { get; set; }
    }
}
